### ISSUE TITLE
Updating the code architecture to MVVM.

### ISSUE THREAD

**Issue by plazzy99** [AbsurdNerd/SimplifyReports#21]
**Description**
currently, the API call and all backend logic are written in the activity class.
Shift all such related code to the ViewModel class.

**Expected behavior**
All the code that is not UI responsible should move to the respective ViewModel class.

**Actual behavior**
The actual behavior of the application should not change.

**Comment by spacemonkey1101** [comment]
can you assign me this?

**Comment by plazzy99** [comment]
@spacemonkey1101 are you working on this issue?

**Comment by spacemonkey1101** [comment]
yes i would brief u about my proceedings
