### ISSUE TITLE
Docs: Adding Code of Conduct file

### ISSUE THREAD

**Issue by Kerveyfelix** [AbsurdNerd/SimplifyReports#8]
All open-source projects have code of conduct file. Can I make this file for SimplifyReports?

**Comment by Tejas1510** [comment]
@plazzy99 Can I work on it?

**Comment by plazzy99** [comment]
> 
> 
> @plazzy99 Can I work on it?

it is already assigned to @Kerveyfelix 

You can open other issues and assign it to yourself.

**Comment by Tejas1510** [comment]
Sure @plazzy99
